name: env-setup
description: "Set up .env file"

runs:
  using: "composite"
  defaults:
    run:
      working-directory: ./app
  steps:
    - name: create .env from .env.tpl
      shell: bash
      run: |
        cp .env.tpl .env
        echo "NEXT_PUBLIC_SERVER_DID='did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi'" >> .env
